language: go

git:
  autocrlf: false

env:
  global:
    - GO111MODULE=on

go: 1.14.x

arch:
  - amd64
  - arm64

os:
  - linux
  - osx
  - windows

install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0
  - go get github.com/magefile/mage

script:
  - go mod download
  - go mod verify
  - mage -v check
  - curl -sfL https://git.io/goreleaser | sh -s -- check # check goreleaser config for deprecations

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux && $TRAVIS_CPU_ARCH = amd64