language: go

git:
  autocrlf: false

env:
  global:
    - GO111MODULE=on

go: 1.15.3

arch:
  - amd64
  - arm64

os:
  - linux
  - osx
  - windows

install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0

script:
  - go mod download
  - go mod verify
  - go run mage.go -v check

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux && $TRAVIS_CPU_ARCH = amd64