help="""
Golang bolerplate for Travis CI build configuration
"""

[prompts.versions]
type="input"
message="Enter comma-separated Go versions to include in build matrix:"
help="""
Example:
`1.10, 1.11, 1.12, 1.13.x, master`
"""

[prompts.operatingSystems]
type="multi-choice"
message="Select operating systems to include in build matrix:"
options=["linux", "osx", "windows"]

[prompts.cpuArchs]
type="multi-choice"
message="Select CPU architectures to include in build matrix:"
options=["amd64", "arm64", "ppc64le", "s390x"]

